default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 27102003
  host: localhost

development:
  <<: *default
  database: api


test:
  adapter: sqlite3
  database: api_test
  pool: 5
  timeout: 5000